### ISSUE TITLE
Zabbix7.2 doesn't work in Nagstamon 3.16

### ISSUE THREAD

**Issue by project57ua** [HenriWahl/Nagstamon#1107]
I've added the zabbix7.2 to the latest version of nagstamon but it doesn't work.

![Image](https://github.com/user-attachments/assets/83a24ba7-5345-4dac-afe6-64febdc4f977)

Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: (Error -32600: Invalid request., Invalid parameter "/": unexpected parameter "auth". while sending ("jsonrp": "2.0", "method": "trigger.get", "params". ("only_true": true,

Would you plan to add the authorization through API key in the next Nagstamon update?

**Comment by HenriWahl** [comment]
@project57ua can you please try the current testing release?

**Comment by project57ua** [comment]
here is more information from debug logs if it's useful 

` tail -n 40 /home/paul/nagstamon.log
    return self.parent.do_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 301, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorized. while sending {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid", "description", "lastchange", "manual_close"], "selectLastEvent": ["eventid", "name", "ns", "clock", "acknowledged", "value", "severity"], "selectHosts": ["hostid", "host", "name", "status", "available", "maintenance_status", "maintenance_from"], "selectItems": ["name", "lastvalue", "state", "lastclock"], "filter": {"value": 1}}, "id": 33}', -32602)

ERROR: 2025-04-29 23:07:21.027375 Zabbix7.2 Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 157, in _get_status
    services = self.zapi.trigger.get({'only_true': True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 344, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 351, in do_request
    return self.parent.do_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 301, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorized. while sending {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid", "description", "lastchange", "manual_close"], "selectLastEvent": ["eventid", "name", "ns", "clock", "acknowledged", "value", "severity"], "selectHosts": ["hostid", "host", "name", "status", "available", "maintenance_status", "maintenance_from"], "selectItems": ["name", "lastvalue", "state", "lastclock"], "filter": {"value": 1}}, "id": 35}', -32602)

ERROR: 2025-04-29 23:07:47.109748 Zabbix7.2 Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 157, in _get_status
    services = self.zapi.trigger.get({'only_true': True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 344, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 351, in do_request
    return self.parent.do_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Nagstamon/thirdparty/zabbix_api.py", line 301, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
Nagstamon.thirdparty.zabbix_api.ZabbixAPIException: ('Error -32602: Invalid params., Not authorized. while sending {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid", "description", "lastchange", "manual_close"], "selectLastEvent": ["eventid", "name", "ns", "clock", "acknowledged", "value", "severity"], "selectHosts": ["hostid", "host", "name", "status", "available", "maintenance_status", "maintenance_from"], "selectItems": ["name", "lastvalue", "state", "lastclock"], "filter": {"value": 1}}, "id": 37}', -32602)
`

**Comment by HenriWahl** [comment]
@project57ua maybe some of the Zabbix contributors are able to help.

Hey @ProfessorLogout, @Simkimdm, @nautics889, @hunsbea and @grzeg1 - assuming you are still using Zabbix with Nagstamon, do you have any experience with Zabbix 7.2 or an idea why this problem appears?

**Comment by project57ua** [comment]
Hello,

Thank you for your response.
I'm using the latest version  but the error the same

**Comment by project57ua** [comment]
@HenriWahl any ideas how it's can be solved?

**Comment by project57ua** [comment]
Thank you @Simkimdm.
I'll wait once it is implemented in the new release and then I'll check it

**Comment by HenriWahl** [comment]
Thanks to @Simkimdm - please check 3.17-20250526 from https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by project57ua** [comment]
Many thanks for trying to solve this issue. 
But the issue still exist. 
Just want to show you the setting that I use and the error that I'm still getting

![Image](https://github.com/user-attachments/assets/b06ffb94-4911-494e-875e-17ad6b45f768)

![Image](https://github.com/user-attachments/assets/350bdc7f-f271-4197-ab1b-42f3489da354)

here is a screenshot of the user in the zabbix dashboard

![Image](https://github.com/user-attachments/assets/1e3f746d-d64e-473c-984c-e68fae1cfbe0)

here is from API area 

![Image](https://github.com/user-attachments/assets/284852d4-f4df-4a5e-ad95-0cf3d3b3125c)

**Comment by project57ua** [comment]
I've just added zabbix 7.2 (through API)  and zabbix 5 through (U/P authentication) to ZabbixVue extension and it works properly there. But it doesn't useful like nagstamon. I'm wondering if you can check the code from ZabixVue extension and try to implement the API algorithm to Nagstamon 

![Image](https://github.com/user-attachments/assets/b0dfcdc1-6896-4396-bf25-6cbf0ea81ff1)

**Comment by project57ua** [comment]
Hello @Simkimdm 
Thanks for adjustments and for your response. 
Can you please let me know do you use the same settings in the nagstamon or other? 
Also, I'm wondering perhaps this issue is related to some Zabbix configuration.?
Do you use customer Zabbix configuration or a default ? I mean during the installing the Zabbix you have used the default path for installation or custom?
For example I'm using Zabbix default path /usr/share/zabbix for installation 
and /usr/share/zabbix/ui/ for the web interface

Also, perhaps this issue is related to some missed modules on zabbix server?

**Comment by HenriWahl** [comment]
@Simkimdm thank you - this is now merged and built, available as relese 3.17-20250531. @project57ua please check it out.

**Comment by project57ua** [comment]
@HenriWahl @Simkimdm thanks for trying to solve this issue so fast. 
Just downloaded a new version and saw that it didn't solve this issue. Additionaly Zabbix 5 stopped working on that version. 
So I have rollback to 3.17-20250526 since there 5th zabbix generation is working properly. 

![Image](https://github.com/user-attachments/assets/fcf5bfab-1e2e-4486-b28c-3dc8fd4e2b43)

The settings tried to use without /api_jsonrpc.php in the URL

**Comment by project57ua** [comment]
@Simkimdm 
I don't know if it helps but checking through curl the api_jsonrpc.php by using the parameters that provided on zabbix documentation page is getting the following results:

###
paul@mylocalpc~$ curl --request POST   --url 'https://xxx.xx.xx.xx/zabbix/api_jsonrpc.php'   --header 'Content-Type: application/json-rpc'   --data '{"jsonrpc":"2.0","method":"user.login","params":{"username":"nagstamon3","password":"mypass1"},"id":1}'
{"jsonrpc":"2.0","result":"ee4582d0c29743d56a9dd1cd4400239c","id":1}
###

source https://www.zabbix.com/documentation/current/en/manual/api#authentication

**Comment by Simkimdm** [comment]
Hi @project57ua, 
While reworking the authentication checks for the newer zabbix Version, i´ve done a misstake for older Version. Sorry for that. Should be fixed in #1113
Regarding the 7.2 Auth error, there is a fix in Zabbix web gui itself: https://support.zabbix.com/browse/ZBX-22952 or https://www.zabbix.com/documentation/7.2/en/manual/installation/known_issues/#authorization-header-forwarding

**Comment by HenriWahl** [comment]
Thanks @Simkimdm and please @project57ua check latest testing release (still numbered 3.17-20250531).

**Comment by project57ua** [comment]
thanks @HenriWahl 

Still getting the same error. but I see that the method of checking is another

(<class 'Nagstamon.thirdparty.zabbix_api.ZabbixAPIException'>, ZabbixAPIException('Error -32602: Invalid params., Not authorized. while sending {"jsonrpc": "2.0", "method": "maintenance.get", "params": {"output": ["active_since", "active_till", "tags"], "selectTags": "extend"}, "id": 2}', -32602), <traceback object at 0x76cbb7051dc0>)


Can you please specify: are you using AlmaLinux 9? Perhaps this issue is related to the version of the OS.....

**Comment by project57ua** [comment]
Thanks @HenriWahl and @Simkimdm 

at the first view, it is  better since no errors anymore

Its just shows "OK"

![Image](https://github.com/user-attachments/assets/5cf70ebf-fec7-4883-afe0-f6f5865dfc08)

But actually, zabbix does report about some critical problems 

![Image](https://github.com/user-attachments/assets/bcd71013-420f-49ef-bd1b-ae6c5bdb23fa)

In the logs it looks following:

`DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf92e0> for state "OK"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9250> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9370> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9400> for state "WARNING"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9490> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9520> for state "HIGH"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf95b0> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9640> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf96d0> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf9760> for state "DOWN"
DEBUG: SystemTrayIcon created icon <Nagstamon.QUI.QIconWithFilename object at 0x7da7ffbf97f0> for state "ERROR"
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '7.2.7', 'id': 0}
20: Zabbix API version: 7.2.7
10: Trying to login with 'nagstamon3':'sha256(90ef49eb731ea03cf4042e76f68770e4a958f54cdeb88e12fccd9adcaffcad4b)'
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.login', 'params': {'username': 'nagstamon3', 'password': 'I_hide_pass'}, 'id': 1}
20: Sending: {"jsonrpc": "2.0", "method": "user.login", "params": {"username": "nagstamon3", "password": "I_hide_pass"}, "id": 1}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api', 'Authorization': 'Bearer '}
DEBUG: 2025-06-03 03:49:20.298029 Zabbix7.2 fetch_url: https://nagstamon.de/version/unstable CGI Data: None
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': '590e0c01dbec47046cf14d646abf1687', 'id': 1}
10: json_obj: {'jsonrpc': '2.0', 'method': 'maintenance.get', 'params': {'output': ['active_since', 'active_till', 'tags'], 'selectTags': 'extend'}, 'id': 2}
20: Sending: {"jsonrpc": "2.0", "method": "maintenance.get", "params": {"output": ["active_since", "active_till", "tags"], "selectTags": "extend"}, "id": 2}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api', 'Authorization': 'Bearer 590e0c01dbec47046cf14d646abf1687'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 2}
10: json_obj: {'jsonrpc': '2.0', 'method': 'trigger.get', 'params': {'only_true': True, 'skipDependent': True, 'monitored': True, 'active': True, 'output': ['triggerid']}, 'id': 3}
20: Sending: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"]}, "id": 3}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api', 'Authorization': 'Bearer 590e0c01dbec47046cf14d646abf1687'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 3}
10: json_obj: {'jsonrpc': '2.0', 'method': 'user.checkAuthentication', 'params': {'sessionid': '590e0c01dbec47046cf14d646abf1687'}, 'id': 4}
20: Sending: {"jsonrpc": "2.0", "method": "user.checkAuthentication", "params": {"sessionid": "590e0c01dbec47046cf14d646abf1687"}, "id": 4}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api'}
DEBUG: 2025-06-03 03:50:08.611387 Zabbix7.2 Refreshing all hosts and services
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': {'userid': '7', 'username': 'nagstamon3', 'name': '', 'surname': '', 'url': '', 'autologin': '1', 'autologout': '0', 'lang': 'en_US', 'refresh': '30s', 'theme': 'default', 'attempt_failed': '0', 'attempt_ip': '32.168.79.238', 'attempt_clock': '1748738133', 'rows_per_page': '50', 'timezone': 'America/Chicago', 'roleid': '2', 'userdirectoryid': '0', 'ts_provisioned': '0', 'debug_mode': 0, 'deprovisioned': False, 'gui_access': 0, 'mfaid': 0, 'auth_type': 0, 'type': 2, 'userip': '8.18.158.182', 'sessionid': '590e0c01dbec47046cf14d646abf1687', 'secret': 'eb3ef59da7f80fd29c2aeda29893cd45'}, 'id': 4}

`

So in summary, in that version no error but no alerts from Zabbix also...

**Comment by project57ua** [comment]
Perhaps here is an issues

10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 2}


I see the result is empty.

**Comment by project57ua** [comment]
When I use Zabbix5 in the nagstamon, I see the following 

10: Response Body: {'jsonrpc': '2.0', 'result': [{'triggerid': '31489', 'description': 'Critical - Load average: ({ITEM.LASTVALUE1} {ITEM.LASTVALUE2} {ITEM.LASTVALUE3})', 'lastchange': '1747486831', 'manual_close': '1', 'hosts': [{'hostid': '10566', 'host': 'servers1.dreamhost.net', 'name': 'server3.dreamhost.net', 'status': '0', 'available': '1', 'maintenance_status': '0', 'maintenance_from': '0'}], 'items': [{'itemid': '62911', 'name': 'Load average (15m avg)', 'state': '0', 'lastclock': '1748912911', 'lastvalue': '45.21'}, {'itemid': '62912', 'name': 'Load average (1m avg)', 'state': '0', 'lastclock': '1748912913', 'lastvalue': '29.8'}, {'itemid': '62913', 'name': 'Load average (5m avg)', 'state': '0', 'lastclock': '1748912913', 'lastvalue': '43.91'}], 'lastEvent': {'ns': '659758925', 'eventid': '5357626', 'name': 'Critical - Load average: (22.1 25.54 35.21)', 'clock': '1747486831', 'acknowledged':  'value': '0', 'severity': '0'}}], 'id': 8}

So for Zabbix7 it is getting the response code 200, but actually the response is empty (or it can't read it)

**Comment by project57ua** [comment]
Changed the permissions for my user from admin to super admin and now it's working
Many thanks @HenriWahl @Simkimdm  for solving this issue.

**Comment by simonkimmigdmde** [comment]
Hi @project57ua, 
nagstamon shouldn´t work just with super admin. 
can you send me a screenshot of your user role settings from zabbix and do your user have write or read permission to the host?

**Comment by project57ua** [comment]
@simonkimmigdmde thank you for helping me with solving this issue
Here is a screenshot of my settings that I'm usually using, and it doesn't work.
![Image](https://github.com/user-attachments/assets/6276d2fa-b612-4cd8-88a9-b4bcf7b8c6ea)
In the logs (with the standard user permissions), I'm seeing the following 

20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 203}
10: json_obj: {'jsonrpc': '2.0', 'method': 'trigger.get', 'params': {'only_true': True, 'skipDependent': True, 'monitored': True, 'active': True, 'output': ['triggerid']}, 'id': 204}
20: Sending: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"]}, "id": 204}
10: Sending headers: {'Content-Type': 'application/json-rpc', 'User-Agent': 'python/zabbix_api', 'Authorization': 'Bearer 10d4a5a7dbb86af183940800b5142dff'}
20: Response Code: 200
10: Response Body: {'jsonrpc': '2.0', 'result': [], 'id': 204}


As you can see, there is no information in the "result [ ]" field. 
But once I set the super admin permissions, it started working properly.

**Comment by HenriWahl** [comment]
Please check https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by project57ua** [comment]
@HenriWahl Thank you for your response. I have downloaded the latest version immediately once it was released, but it doesn't work in general, just doesn't start. So I've rolled back to 20250728 version

**Comment by project57ua** [comment]
also, noticed that it work like though cache, since once I stop zabbix server the nagstamon doesn't show any error or other message, it just tries to refresh till I restart nagtsamon 

<img width="1392" height="343" alt="Image" src="https://github.com/user-attachments/assets/4b107490-abd4-4e51-ae04-3a527335eabc" />

**Comment by project57ua** [comment]
@HenriWahl @Simkimdm just checked the latest version which is 3.17-20250821 and noticed that it only works for super admin user of zabbix. Once I have set the other user type like just admin it is stop working:

Here is a logs when the set "admin" permissions for zabbix user:

###
```
DEBUG: 2025-08-25 20:55:38.569367 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"]}, "id": 1}
DEBUG: 2025-08-25 20:56:03.964262 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "apiinfo.version", "params": {}, "id": 1}
DEBUG: 2025-08-25 20:56:04.300748 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "user.checkAuthentication", "params": {"sessionid": "eb76a44ffae457f4c04af8913e2a7175"}, "id": 1}
ERROR: 2025-08-25 20:56:04.713626 Zabbix7.2 Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 133, in check_authentication
    if result['error']:
       ~~~~~~^^^^^^^^^
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 82, in init_HTTP
    self.check_authentication()
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Zabbix.py", line 136, in check_authentication
    raise RuntimeError(f"Authentication check failed: {str(e)}")
RuntimeError: Authentication check failed: 'error'

DEBUG: 2025-08-25 20:56:04.714073 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"]}, "id": 1}
```
###

Once I have set a "super admin" permissions then it is starting work properly:

###
```
DEBUG: 2025-08-25 20:50:25.958140 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "apiinfo.version", "params": {}, "id": 1}
DEBUG: 2025-08-25 20:50:26.076039 Zabbix7.2 fetch_url: https://nagstamon.de/version/unstable CGI Data: None
DEBUG: 2025-08-25 20:50:26.301757 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "user.checkAuthentication", "params": {"sessionid": ""}, "id": 1}
DEBUG: 2025-08-25 20:50:26.664413 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "user.login", "params": {"username": "nagstamon", "password": "hidden_pass"}, "id": 1}
DEBUG: 2025-08-25 20:50:27.080078 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid"]}, "id": 1}
DEBUG: 2025-08-25 20:50:27.454859 Zabbix7.2 fetch_url: http://hidden_ip/zabbix/api_jsonrpc.php CGI Data: {"jsonrpc": "2.0", "method": "trigger.get", "params": {"only_true": true, "skipDependent": true, "monitored": true, "active": true, "output": ["triggerid", "description", "lastchange", "manual_close"], "triggerids": ["26175", "26691", "29468", "28201", "26630", "28567", "28445", "29529", "28079", "28506", "28262", "25392", "25881", "28140"], "selectLastEvent": ["eventid", "name", "ns", "clock", "acknowledged", "value", "severity"], "selectHosts": ["hostid", "host", "name", "status", "available", "active_available", "maintenance_status", "maintenance_from"], "selectItems": ["name", "lastvalue", "state", "lastclock"]}, "id": 1}

```###

**Comment by project57ua** [comment]
@HenriWahl @Simkimdm just checked the latest version which is 3.17-20250911 and issue with "user role" is still exist.
when I use the User role/Admin role and it doesn't show any result.
But once I set the permissions Super Admin role, it shows the information about services properly in the nagstamon.

**Comment by project57ua** [comment]
@HenriWahl @Simkimdm just checked the latest version which is 3.17-20250923 and issue with "user role" is still exist.
it doesn't work with any other users that different than "Super admin role". In other words only "Super admin role" is working.

**Comment by Simkimdm** [comment]
Hi @project57ua,
i cant reproduce your problem with version 7.0, 7.2 and. 7.4.
Are you still getting the same error? did you allow api access to normal users?
