### ISSUE TITLE
IcingaDBWeb  server

### ISSUE THREAD

**Issue by sasbibic** [HenriWahl/Nagstamon#1116]
When extracting IP of host for custom actions, $ADDRESS$ contains icinga host name instead of IP. I think problem is in:

IcingaDBWed.py where is at line 801, function get_host, this code:
`            ip = result["host_address"]`

JSON returned from Icinga contains field **address** and not field **host_address**

Is there a possibility to fix this ?

Regards
/Sas

**Comment by HenriWahl** [comment]
@sasbibic thanks for the hint - fixed in latest testing release at https://github.com/HenriWahl/Nagstamon/releases/download/latest

**Comment by sasbibic** [comment]
This was a really quick reaction, but sadly the problem is not fixed.  Code seems untouched on Git.
Thank You.

Regards
/Sas

**Comment by HenriWahl** [comment]
@sasbibic as you said I fixed in IcingaWebDB.py 😄  - but now in IcingaWeb2.py too. Please check latest testing release when https://github.com/HenriWahl/Nagstamon/actions/runs/15629020282 is completed.

**Comment by sasbibic** [comment]
@HenriWahl but I'm using IcingaWebDB ??

**Comment by HenriWahl** [comment]
Sorry but I don't find any "host_address" in branch https://github.com/HenriWahl/Nagstamon/tree/3.17-20250612

**Comment by sasbibic** [comment]
I've screwed up. It was missing correct option for Connection method in Actions !! Now works perfectly !!!

Thank You!!

**Comment by HenriWahl** [comment]
So it shall be `result["address"]` in `IcingaWebDB.py` **AND** `IcingaWeb2.py` now?

**Comment by sasbibic** [comment]
Yes. That's what returned JSON says.

Regards
/Saš
