### ISSUE TITLE
Trying to autosend emails

### ISSUE THREAD

**Issue by cerberus10** [HenriWahl/Nagstamon#454]
Hi I  am trying to make nagstamon autosend emails through the notification, action string but I am not sure  how what I put there is executed or what is the apropiate way to achive this inside the program.  

For example  if  I use a mailto link it opens  my  outllook but doesnt  autosend it 

Should I  try using sendmail library in python, if so how should I execute a python script from the action string  parameter. 

Thanks for your help Henri, this is truly a lifesaving tool . 

+

**Comment by HenriWahl** [comment]
Shouldn't your monitoring send the notification mails anyway?

**Comment by cerberus10** [comment]
I dont have the permissions (issues where i work ), so im trying to get a
work around so that everybody can be a little happier here .

So far I only have 1 question is there a way to add a conditional timer to
the execution of the action like if "warning" state remains after 5 minutes
then send the mail . Like a daemon .


Thank you for answering Henri, this program has been a life saver for me
and other IT slaves.

**Comment by HenriWahl** [comment]
No, it just can start an action when an event happens because of being pretty passive and only showing the server info. A built-in delay might be a task for the executed script.

**Comment by cerberus10** [comment]
Thank you for your answer .
Okay, but using placeholders as sysarg should work ??.
 Like $Host in "python email. py $Host " so that I can pass info of nagiis
to urllib.

**Comment by HenriWahl** [comment]
Sorry, this looks like a bug - I need some time to check this out.

**Comment by HenriWahl** [comment]
I fixed some in latest commit.
In your apparent version you might try omething like
Action string: `/usr/local/bin/my_action.sh '$EVENTS$'`
Running one single action per Event shoud be activated.
It is important to have the $EVENTS$ quoted by ' to get it into action script with spaces because the string given to the script will look like `Home monitor server2 Interface 10 WARNING`.
Not much but at least some information to be sent somewhere.

**Comment by cerberus10** [comment]
Just checked the latest unstable and still having issues with the place holders I am using something like this in the  notification action section. 

/usr/lib/python script.py    '$HOST$'   '$MONITOR-CGI$'

BUT THE PLACEHOLDERS ARE EMPTY, I have tested my script and know that the placeholders are not being updated from nagstamon.

Any ideas???

Thanks for your help and support you are doing a truly amazing job.

**Comment by HenriWahl** [comment]
Sorry, some misunderstanding: the '$EVENT$' variable now works and will deliver a string with all information included. The $HOST$ and others do not - yet.

**Comment by cerberus10** [comment]
Hi I am using nagstamon 3.1-20171030  (unstable) and the issue with passing "$EVENT$" OR  '$EVENT$' , i HAVE TRIED BOTH DOESNT SEEM TO WORK.  

My scripts debug gets just the placeholder from nagstamon. 

I am using the wrong unstable or is the issue still persistent

**Comment by HenriWahl** [comment]
Did you use binary release? There these fixes weren't included yet. At the moment I do compile a new binary release. I will let you know it it is ready.

**Comment by HenriWahl** [comment]
Please check with binaries from https://nagstamon.ifw-dresden.de/files/incoming/.

**Comment by cerberus10** [comment]
I had already cloned the github repo but this is even better . I cant thank
you enough Henri, the events variable has been a life saver. Now with my
python script I can get email notifications easily.
You are a truly dedicated developer.
